//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SachOnlineAD {
    
    
    public partial class _Default {
        
        /// <summary>
        /// AnhTruotAD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SachOnlineAD.AnhTruotAD AnhTruotAD;
        
        /// <summary>
        /// InfoAD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SachOnlineAD.InfoAD InfoAD;
        
        /// <summary>
        /// DanhMucSachAD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SachOnlineAD.DanhMucSachAD DanhMucSachAD;
    }
}
